#!/usr/bin/env python3
"""Generate the local MCP block for Hermes."""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = Path(
    os.environ.get("MCP_CONFIG_OUTPUT", ROOT / ".local" / "hermes-mcp.yaml")
).expanduser()


def yaml_string(value: Path | str) -> str:
    """JSON strings are valid YAML strings and escape paths predictably."""
    return json.dumps(str(value), ensure_ascii=False)


def entrypoint(service: str, command: str) -> Path:
    return ROOT / "mcp" / service / ".venv" / "bin" / command


def env_file(service: str) -> Path:
    return ROOT / "mcp" / service / ".env"


def render() -> str:
    calendar = yaml_string(entrypoint("calendar", "calendar-mcp"))
    email = yaml_string(entrypoint("email", "email-mcp"))
    homeassistant = yaml_string(entrypoint("homeassistant", "homeassistant-mcp"))
    obsidian = yaml_string(entrypoint("obsidian", "obsidian-mcp"))
    telegram = yaml_string(entrypoint("telegram", "telegram-mcp"))
    calendar_env = yaml_string(env_file("calendar"))
    email_env = yaml_string(env_file("email"))
    homeassistant_env = yaml_string(env_file("homeassistant"))
    obsidian_env = yaml_string(env_file("obsidian"))
    telegram_env = yaml_string(env_file("telegram"))

    return f"""# Generated by deployment/generate_config.py. No secrets are stored here.
# Merge these entries into the intended profile's ~/.hermes/config.yaml.
mcp_servers:
  calendar:
    command: {calendar}
    env:
      MCP_ENV_FILE: {calendar_env}
    enabled: true
    trust: full
    connect_timeout: 30
  email:
    command: {email}
    env:
      MCP_ENV_FILE: {email_env}
    enabled: true
    trust: full
    connect_timeout: 30
  telegram:
    command: {telegram}
    env:
      MCP_ENV_FILE: {telegram_env}
    enabled: true
    trust: full
    connect_timeout: 60
  home_assistant:
    command: {homeassistant}
    env:
      MCP_ENV_FILE: {homeassistant_env}
    enabled: true
    trust: full
    connect_timeout: 30
  obsidian:
    command: {obsidian}
    env:
      MCP_ENV_FILE: {obsidian_env}
    enabled: true
    trust: full
    connect_timeout: 30
  vkusvill:
    url: "https://mcp.vkusvill.ru/mcp"
    enabled: true
    trust: untrusted
    connect_timeout: 30
"""


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    OUTPUT.write_text(render(), encoding="utf-8")
    os.chmod(OUTPUT, 0o600)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
